{
 "title": "K8S - Overview",
 "tags": [
  "k8s",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_namespace_labels, kubernetes_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "count ( kube_node_status_condition{condition=\"Ready\",kubernetes_cluster_name=\"$cluster\",status=\"true\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Total pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "count(kube_pod_status_phase{kubernetes_cluster_name=\"$cluster\", phase=\"Running\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Total endpoints",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "count(kube_endpoint_created{kubernetes_cluster_name=\"$cluster\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Total containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "count(kube_pod_container_info{kubernetes_cluster_name=\"$cluster\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU requests %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(sum(kube_pod_container_resource_requests{resource=\"cpu\",kubernetes_cluster_name=\"$cluster\"}) by (namespace, pod, node) * sum(kube_pod_info{created_by_kind!=\"Job\",kubernetes_cluster_name=\"$cluster\"}) by (namespace, pod, node)) / sum(kube_node_status_allocatable{resource=\"cpu\",kubernetes_cluster_name=\"$cluster\"}) * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU real utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(irate(container_cpu_usage_seconds_total{kubernetes_cluster_name=\"$cluster\",namespace!=\"\",container_name=\"\"}[10m])) / sum(kube_node_status_capacity{resource=\"cpu\",kubernetes_cluster_name=\"$cluster\"}) * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\", kubernetes_cluster_name=\"$cluster\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", kubernetes_cluster_name=\"$cluster\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", kubernetes_cluster_name=\"$cluster\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU Real",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(irate(container_cpu_usage_seconds_total{kubernetes_cluster_name=\"$cluster\",namespace!=\"\",container_name=\"\"}[10m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Memory requests %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(sum(kube_pod_container_resource_requests{resource=\"memory\",kubernetes_cluster_name=\"$cluster\"}) by (namespace, pod, node) * sum(kube_pod_info{created_by_kind!=\"Job\",kubernetes_cluster_name=\"$cluster\"}) by (namespace, pod, node))  / sum(kube_node_status_allocatable{resource=\"memory\",kubernetes_cluster_name=\"$cluster\"}) * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Memory real utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(container_memory_usage_bytes{kubernetes_cluster_name=\"$cluster\",namespace!=\"\",container_name=\"\"}) / sum(kube_node_status_capacity{resource=\"memory\",kubernetes_cluster_name=\"$cluster\"}) * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Memory capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(kube_node_status_capacity{resource=\"memory\", kubernetes_cluster_name=\"$cluster\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Memory requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", kubernetes_cluster_name=\"$cluster\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", kubernetes_cluster_name=\"$cluster\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Memory real",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(container_memory_usage_bytes{kubernetes_cluster_name=\"$cluster\",namespace!=\"\",container_name=\"\"})\n",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "Cluster General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Number of nodes by state",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{kubernetes_cluster_name=\"$cluster\",status=\"true\"}) by (condition)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Number of pods by state",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{kubernetes_cluster_name=\"$cluster\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Number of pods by waiting reason",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_reason{kubernetes_cluster_name=\"$cluster\"}) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Average pods per node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_info{kubernetes_cluster_name=\"$cluster\"})  / sum(kube_node_info{kubernetes_cluster_name=\"$cluster\"})",
     "legendFormat": "Average pods per node"
    }
   ]
  },
  {
   "title": "Total number of containers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_container_info{kubernetes_cluster_name=\"$cluster\"})",
     "legendFormat": "Total number of containers"
    }
   ]
  },
  {
   "title": "Total number of endpoints",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_endpoint_created{kubernetes_cluster_name=\"$cluster\"})",
     "legendFormat": "Total number of endpoints"
    }
   ]
  },
  { "title": "Cluster General - Extended", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Active nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_condition{kubernetes_cluster_name=\"$cluster\", condition=\"Ready\", status=\"true\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Active namespaces",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(kube_namespace_status_phase{kubernetes_cluster_name=\"$cluster\",phase=\"Active\"}) by (namespace)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{namespaces}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "CPU/Mem Request/Limit/Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "CPU requests & capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(sum(kube_pod_container_resource_requests_cpu_cores{kubernetes_cluster_name=\"$cluster\"}) by (namespace, pod, node) * sum(kube_pod_info{created_by_kind!=\"Job\",kubernetes_cluster_name=\"$cluster\"}) by (namespace, pod, node))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "CPU pod requests ",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "sum(kube_node_status_allocatable_cpu_cores{kubernetes_cluster_name=\"$cluster\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "CPU nodes capacity ",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{kubernetes_cluster_name=\"$cluster\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "CPU pod limits",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "sum(kube_resourcequota{kubernetes_cluster_name=\"$cluster\",resource=\"requests.cpu\",type=\"hard\"})",
     "legendFormat": "CPU namespace requests"
    },
    {
     "expr": "sum(kube_resourcequota{kubernetes_cluster_name=\"$cluster\",resource=\"limits.cpu\",type=\"hard\"})",
     "legendFormat": "CPU namespace limits"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{kubernetes_cluster_name=\"$cluster\",namespace!=\"\",container_name=\"\"}[10m]))",
     "legendFormat": "CPU real usage"
    }
   ]
  },
  {
   "title": "Memory requests & capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(sum(kube_pod_container_resource_requests_memory_bytes{kubernetes_cluster_name=\"$cluster\"}) by (namespace, pod, node) * sum(kube_pod_info{created_by_kind!=\"Job\",kubernetes_cluster_name=\"$cluster\"}) by (namespace, pod, node))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Memory pod requests",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "sum(kube_node_status_allocatable_memory_bytes{kubernetes_cluster_name=\"$cluster\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Memory node capacity ",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{kubernetes_cluster_name=\"$cluster\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Memory pod limits",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "sum(kube_resourcequota{kubernetes_cluster_name=\"$cluster\",resource=\"requests.memory\",type=\"hard\"})",
     "legendFormat": "Memory namespace requests"
    },
    {
     "expr": "sum(kube_resourcequota{kubernetes_cluster_name=\"$cluster\",resource=\"limits.memory\", type=\"hard\"})",
     "legendFormat": "Memory namespace limits"
    },
    {
     "expr": "sum(container_memory_usage_bytes{kubernetes_cluster_name=\"$cluster\",namespace!=\"\",container_name=\"\"})\n",
     "legendFormat": "Memory real usage"
    }
   ]
  },
  {
   "title": "Requests utilization",
   "type": "graph",
   "description": "Used requests / Cluster allocateable resources",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(sum(kube_pod_container_resource_requests{resource=\"cpu\",kubernetes_cluster_name=\"$cluster\"}) by (namespace, pod, node) * sum(kube_pod_info{created_by_kind!=\"Job\",kubernetes_cluster_name=\"$cluster\"}) by (namespace, pod, node)) / sum(kube_node_status_allocatable{resource=\"cpu\",kubernetes_cluster_name=\"$cluster\"}) * 100\n",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "CPU",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "sum(sum(kube_pod_container_resource_requests{resource=\"memory\",kubernetes_cluster_name=\"$cluster\"}) by (namespace, pod, node) * sum(kube_pod_info{created_by_kind!=\"Job\",kubernetes_cluster_name=\"$cluster\"}) by (namespace, pod, node))  / sum(kube_node_status_allocatable{resource=\"memory\",kubernetes_cluster_name=\"$cluster\"}) * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Memory",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Cluster utilization",
   "type": "graph",
   "description": "Real utilization / cluster capacity",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(irate(container_cpu_usage_seconds_total{kubernetes_cluster_name=\"$cluster\",namespace!=\"\",container_name=\"\"}[10m]))  / sum(kube_node_status_capacity{resource=\"cpu\",kubernetes_cluster_name=\"$cluster\"}) * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "CPU",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "sum(container_memory_usage_bytes{kubernetes_cluster_name=\"$cluster\",namespace!=\"\",container_name=\"\"})  / sum(kube_node_status_capacity{resource=\"memory\",kubernetes_cluster_name=\"$cluster\"}) * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Memory",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Top 20 Namespaces - CPU waste",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "topk(20, sum(kube_pod_container_resource_requests{resource=\"cpu\",kubernetes_cluster_name=\"$cluster\"}) by (namespace) - sum(irate(container_cpu_usage_seconds_total{kubernetes_cluster_name=\"$cluster\",namespace!=\"\",container_name=\"\"}[10m])) by (namespace))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{namespace}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Top 20 Namespaces - Memory waste",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "topk(20, sum(container_memory_usage_bytes{kubernetes_cluster_name=\"$cluster\",namespace!=\"\"}) by (namespace) - sum(kube_pod_container_resource_requests{resource=\"memory\",kubernetes_cluster_name=\"$cluster\"}) by (namespace))\r",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{namespace}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Top 20 CPU usage - Pods in namespaces",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "topk(20, sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",pod!=\"\"}[10m])) by (pod,namespace))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{namespace - pod}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Top 20 Memory usage - Pods in namespaces",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "topk(20, sum(rate(container_memory_usage_bytes{container_name!=\"POD\",pod!=\"\"}[10m])) by (pod,namespace))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{namespace - pod}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "PVCs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "PVCs by phase",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(kube_persistentvolumeclaim_status_phase{kubernetes_cluster_name=\"$cluster\"}) by (phase)\n\n",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{phase}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "PVs by phase",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(kube_persistentvolume_status_phase{kubernetes_cluster_name=\"$cluster\"}) by (phase)\n",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{phase}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}